# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

# Copia apenas o csproj e restaura dependências
COPY ["api.csproj", "./"]
RUN dotnet restore "api.csproj"

# Copia todo o restante do código
COPY . .
RUN dotnet publish "api.csproj" -c Release -o /app/publish

# Etapa final
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "api.dll"]
