# Imagem oficial do .NET Runtime
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 8080  # Porta padrão do Render

# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

# Copia apenas o csproj e restaura dependências
COPY ["api/api.csproj", "api/"]
RUN dotnet restore "api/api.csproj"

# Copia todo o restante do código
COPY . .
WORKDIR "/src/api"

# Build e publish
RUN dotnet publish "api.csproj" -c Release -o /app/publish

# Final Stage
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "api.dll"]
